version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra

  image-metadata-service:
    build: ./img-metadata-service
    container_name: image-metadata-service
    depends_on:
      - cassandra
      - logstash
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=cassandra://cassandra-db:9042
      - SPRING_PROFILES_ACTIVE=docker


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - elk
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.9  # Use the latest available version
    container_name: etcd
    restart: always
    ports:
      - "2379:2379"  # Client communication port
      - "2380:2380"  # Peer communication port (for clustering)
    command: |
      etcd --name etcd-node \
           --data-dir /etcd-data \
           --listen-client-urls http://0.0.0.0:2379 \
           --advertise-client-urls http://0.0.0.0:2379 \
           --listen-peer-urls http://0.0.0.0:2380 \
           --initial-advertise-peer-urls http://0.0.0.0:2380 \
           --initial-cluster etcd-node=http://0.0.0.0:2380 \
           --initial-cluster-state new \
           --initial-cluster-token etcd-cluster
    volumes:
      - etcd-data:/etcd-data

volumes:
  cassandra-data:
  esdata:
  etcd-data:

networks:
  cassandra-network:
    driver: bridge
  elk:
    driver: bridge
